export const SAVE_EDUCATIONAL_EXPERIENCES_REQUEST = "SAVE_EDUCATIONAL_EXPERIENCES_REQUEST";
export const SAVE_EDUCATIONAL_EXPERIENCES_SUCCESS = "SAVE_EDUCATIONAL_EXPERIENCES_SUCCESS";
export const SAVE_EDUCATIONAL_EXPERIENCES_FAILED = "SAVE_EDUCATIONAL_EXPERIENCES_FAILED";

export const GET_UNIVERSITIES_REQUEST = "GET_UNIVERSITIES_REQUEST";
export const GET_UNIVERSITIES_SUCCESS = "GET_UNIVERSITIES_SUCCESS";
export const GET_UNIVERSITIES_FAILED = "GET_UNIVERSITIES_FAILED";